language: php

services:
  - docker

script:
  - make test-docker

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  - version=5.6
  - version=7.0
  - version=7.1
  - version=7.2
  - version=7.3
  - version=7.4

notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms: $SLACK_TOKEN
